### ISSUE TITLE
Catkin build fail

### ISSUE THREAD

**Issue by vincent-mayer** [Qianboy/hithand_ros#1]
Hi Qian,

the installation instructions should be updated. I followed them and the build failed. This is because the make file expects a different folder structure in `src/`. The packages `hithand_control  hithand_description  hithand_gazebo` should be in `src/hithand_ros` instead of `src/`.

**Comment by qqianfeng** [comment]
This error cannot be duplicated. If any user has this error, it will be welcome to post the error here and give the feedback of this solution.
